services:
  external-ecs-sd:
    container_name: external-ecs-sd
    image: xxx
    command:
      - -l=warn
      - -i=20
      - -c=xxxx
      - -s=xxxx
      - -f=/tmp/external_ecs_file_sd.yml
    #build:
    #  context: .
     # dockerfile: Dockerfile
    environment:
      # aws-vault exec profile -n -- docker-compose up -d
      AWS_DEFAULT_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: xxx
      AWS_SECRET_ACCESS_KEY: xxx
      # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    volumes:
      #- ./prometheus-ecs-sd.py:/usr/src/app/prometheus-ecs-sd.py
      - ./tmp/:/tmp/
    ports:
      - 8888:8080

  internal-ecs-sd:
    container_name: internal-ecs-sd
    image: xxxx
    command:
      - -l=warn
      - -i=20
      - -c=xxxx
      - -s=xxxx
      - -f=/tmp/interternal_ecs_file_sd.yml
    #build:
    #  context: .
     # dockerfile: Dockerfile
    environment:
      # aws-vault exec profile -n -- docker-compose up -d
      AWS_DEFAULT_REGION: xxx
      AWS_ACCESS_KEY_ID: xxxx
      AWS_SECRET_ACCESS_KEY: xxxx
      # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    volumes:
      #- ./prometheus-ecs-sd.py:/usr/src/app/prometheus-ecs-sd.py
      - ./tmp/:/tmp/
    ports:
      - 8889:8080
