version: '2.4'
services:

  ecs-sd:
    container_name: ecs-sd
    image: sepa/ecs-sd
    command:
      - -l=debug
      - -i=10
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # aws-vault exec profile -n -- docker-compose up -d
      # curl -X POST localhost:9106/-/reload
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./prometheus-ecs-sd.py:/usr/src/app/prometheus-ecs-sd.py
      - /tmp/:/tmp/
    ports:
    - 8080:8080
